using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppsWorld.ReceiptModule.Infra
{
    public static class ReceiptLoggingValidation
    {
        public const string Enter_Into_SaveReceipt_Method = "Enter Into SaveReceipt Method";
        public const string Enter_Into_If_Condition_Of_The_Receipt_And_Check_Receipt_Is_Not_Null = "Enter Into If Condition Of The Receipt And Check Receipt Is Not Null";
        public const string Enter_Into_Insert_Receipt_Method = "Enter Into Insert Receipt Method";
        public const string Come_Out_From_Insert_Receipt_Bill = "Come Out From Insert Receipt Bill";
        public const string Enter_Into_Update_Receipt_Details_Method = "Enter Into Update Receipt Details Method";
        public const string Come_Out_From_Update_Receipt_Details_Method = "Come Out From Update Receipt Details Method";
        public const string Enter_Into_Update_Receipt_Balancing_Items_Method = "Enter Into Update Receipt Balancing Items Method";
        public const string Come_Out_From_Update_Update_Receipt_Balancing_Items_Method = "Come Out From Update Update Receipt Balancing Items Method";
        public const string Inter_Into_Update_Receipt_GST_Details_Method = "Inter Into Update Receipt GST Details Method";
        public const string Enter_Into_Fill_Method_Of_Fill_Journal_Method = "Enter Into Fill Method Of Fill Journal Method";
        public const string Come_Out_From_Fill_Method_Of_Journal_Method = "Come Out From Fill Method Of Journal Method";
        public const string Enter_Save_Method_Of_Receipt = "Enter Save Method Of Receipt";
        public const string Come_Out_From_Save_Method_Of_Save_Method = "Come Out From Save Method Of Save Method";
        public const string Enter_Into_Else_Of_the_Receipt_Save_Method = "Enter Into Else Of the Receipt Save Method";
        public const string Enter_Into_Else_And_Insert_Receipt_Method = "Enter Into Else And Insert Receipt Method";
        public const string Come_Out_From_Insert_Receipt_In_Else_Of_SaveReceptMethod = "Come Out From Insert Receipt In Else Of SaveReceptMethod";
        public const string Enter_Into_If_And_Check_ReceiptDetails_Is_Not_Null = "Enter Into If And Check ReceiptDetails Is Not Null";
        public const string Enter_Into_Foreach_Of_ReceiptDetails = "Enter Into Foreach Of ReceiptDetails";
        public const string Enter_Into_ReceiptDetails_And_Check_DocumentType_Is_Equal_To_Invoice_Or_Not = "Enter Into ReceiptDetails And Check DocumentType Is Equal To Invoice Or Not";
        public const string Enter_Into_ReceiptDetails_And_Check_AmmountDue_Is_Equal_To_Invoice_Or_Not = "Enter Into ReceiptDetails And Check AmmountDue Is Equal To Invoice Or Not";
        public const string Enter_Into_ReceiptDetails_And_Check_invoice_Is_Not_Equal_To_Null_Or_Not = "Enter Into ReceiptDetails And Check invoice Is Not Equal To Null Or Not";
        public const string Enter_Else_Of_The_ReceiptDetails_And_Check_AmmountDue_Is_Not_Equal_To_ReceiptAmountOr_Not = "Enter Else Of The ReceiptDetails And Check AmmountDue Is Not Equal To ReceiptAmountOr Not";
        public const string Enter_Else_Of_The_ReceiptDetails_And_Check_DocumentType_Is_Equal_To_DebitNote_Are_Not = "Enter Else Of The ReceiptDetails And Check DocumentType Is Equal To DebitNote Are Not";
        public const string Enter_Into_Foreach_of_ReceiptDetails_And_Check_ReceiptAmount_Is_Not_Equal_To_Or_Not = "Enter Into Foreach of else ReceiptDetails And Check ReceiptAmount Is Not Equal To Or_Not";
        public const string Enter_Into_Foreach_of_else_ReceiptDetails_And_Check_AmmountDue_Is_Equal_To_ReceiptAmount_Or_Not = "Enter Into Foreach of else ReceiptDetails And Check AmmountDue Is Equal To ReceiptAmount Or Not";
        public const string Enter_Into_Foreach_of_else_ReceiptDetails_And_Check_invoice_Is_Not_Equal_To_Null_Or_Not = "Enter Into Foreach of else ReceiptDetails And Check invoice Is Not Equal To Null Or Not";
        public const string Enter_Into_Foreach_of_else_ReceiptDetails_And_Check_AmmountDue_Is_Not_Equal_To_AmmountDue_Or_Not = "Enter Into Foreach of else ReceiptDetails And Check AmmountDue Is Not Equal To AmmountDue Or Not";
        public const string Entre_If_Of_ReceiptModel_And_Check_ReceiptBalancingItems_Count_Graterthan_zero_OR_ReceiptBalancingItems_Count_Not_Equal_To_Null = "Entre If Of ReceiptModel And Check ReceiptBalancingItems Count Graterthan zero OR ReceiptBalancingItems Count Not Equal To Null";
        public const string Entre_Foreach_Of_ReceiptBalancingItem = "Entre Foreach Of ReceiptBalancingItem";
        public const string Enter_If_of_ReceiptGSTDetails_And_Check_ReceiptGSTDetails_Is_Not_Equal_To_Null_Or_Not = "Enter If of ReceiptGSTDetails And Check ReceiptGSTDetails Is Not Equal To Null Or Not";
        public const string Enter_Foreach_Of_ReceiptGSTDetail = "Enter Foreach Of ReceiptGSTDetail";
        public const string Enter_Fill_Journal_Method = "Enter Fill Journal Method";
        public const string Come_Out_FromJournal_Method = "Come Out FromJournal Method";
        public const string Enter_Form_Save_Method_Of_Receipt = "Enter Form Save Method Of Receipt";
        public const string Come_Out_From_SavereceiptJv = "Come Out From SavereceiptJv";
        public const string Enter_Into_Try_Block_OF_The_Receip_Call = "Enter Into Try Block OF The Receipt Call";
        public const string Enter_Into_If_Condition_And_Check_Event_Store_Of_Save_Receipt = "Enter Into If Condition And Check Event Store Of Save Receipt";
        public const string Enter_Into_Else_And_Check_Event_Store_Of_SaveReceiptJv = "Enter Into Else And Check Event Store Of SaveReceiptJv";
        public const string Enter_Catch_Block_Of_SaveReceipt_Of_Save_Call = "Enter Catch Block Of SaveReceipt Of Save Call";
        public const string Enter_Into_SaveCreditNoteDocumentVoid_Method = "Enter Into SaveCreditNoteDocumentVoid Method";
        public const string Enter_Into_Not_Null_Of_DocDate_And_CompanyId = "Enter Into Not Null Of DocDate And CompanyId";
        public const string Enter_Into_Try_Of_The_SaveCreditNoteDocumentVoid_Block = "Enter Into Try Of The SaveCreditNoteDocumentVoid Block";
        public const string Enter_Into_SaveReceiptJv_Method = "Enter Into SaveReceiptJv Method";
        public const string Enter_Into_Try_Block_Of_SaveReceiptJv = "Enter Into Try Block Of SaveReceiptJv";
        public const string Entred_Into_Recept_Method_Of_Receipt = "Entred Into Recept Method Of Receipt";
        public const string Entred_If_Condition_Of_Insert_Receipt_And_Check_VarianceExchangeRate_Is_Not_Null = "Entred If Condition Of Insert Receipt And Check VarianceExchangeRate Is Not Null";
        public const string Entred_If_Condition_Of_Insert_Receipt_And_Check_IsGstSettings = "Entred If Condition Of Insert Receipt And Check IsGstSettings";
        public const string End_Of_The_Insert_Receipt = "End Of The Insert Receipt";
        public const string Entred_Into_UpdateReceiptDetails_Method = "Entred Into UpdateReceiptDetails Method";
        public const string Entred_Foreach_Of_ReceiptDetails_Method = "Entred Foreach Of ReceiptDetails Method";
        public const string Enterd_If_Condition_Of_UpdateReceiptDetails_And_Check_RecordStatus_Is_Equals_To_Added = "Enterd If Condition Of UpdateReceiptDetails And Check RecordStatus Is Equals To Added";
        public const string Entred_Into_ElseIf_Of_UpdateReceiptDetails_And_Check_RecordStatus_Not_Equal_To_Added_And_Deleted = "Entred Into ElseIf Of UpdateReceiptDetails And Check RecordStatus Not Equal To Added And Deleted";
        public const string Entred_UpdateReceiptDetails_And_Check_receiptDetail_Not_Equal_To_Null = "Entred UpdateReceiptDetails And Check receiptDetail Not Equal To Null";
        public const string Entered_UpdateReceiptDetails_And_Check_DocumentType = "Entered UpdateReceiptDetails And Check DocumentType";
        public const string Entered_If_Condition_And_Check_ReceiptAmount = "Entered If Condition And Check ReceiptAmount";
        public const string Entered_If_Condition_Of_UpdateDateRecipt_And_Check_receiptDetail_Less_Than_detail = "Entered If Condition Of UpdateDateRecipt And Check receiptDetail Less Than detail";
        public const string Entred_Into_UpdateReceiptDetails_And_Check_Invoice_Is_Not_Equal_To_null_Or_Not = "Entred Into UpdateReceiptDetails And Check Invoice Is Not Equal To null or Not";
        public const string Entred_Into_UpdateReceiptDetail_And_Check_GrandTotal_IsEqual_To_BalanceAmount = "Entred Into UpdateReceiptDetail And Check GrandTotal IsEqual To BalanceAmount";
        public const string Entred_Into_UpdateReceiptDetail_And_Check_GrandTotal_GraterThan_To_BalanceAmount = "Entred Into UpdateReceiptDetail And Check GrandTotal GraterThan To BalanceAmount";
        public const string Entred_Else_If_of_The_UpdateReceiptDetails_And_Check_receiptDetail_LessThan_detail = "Entred Else If of The UpdateReceiptDetails And Check receiptDetail LessThan detail";
        public const string Entered_If_Condition_UpdateRedeiptDetails_And_Check_AmmountDue_IsEqualTo_ReceiptAmount = "Entered If Condition UpdateRedeiptDetails And Check AmmountDue IsEqualTo ReceiptAmount";
        public const string Entred_If_Condition_And_Check_Invoice_IsNot_Null_Or_Not = "Entred If Condition And Check Invoice IsNot Null Or Not";
        public const string Entred_ElseIf_Condition_And_Check_AmmountDue_Is_NotEqualTo_ReceiptAmount = "Entred ElseIf Condition And Check AmmountDue Is NotEqualTo ReceiptAmount";
        public const string Entred_IfCondition_Of_UpdateReceiptDetail_And_Check_InVoice_is_not_EqualTo_Null_Or_Not = "Entred IfCondition Of UpdateReceiptDetail And Check InVoice is not EqualTo Null Or Not";
        public const string Entred_ElseIf_Of_DocumentType_And_Check_is_Equlto_DebitNote_Or_Not = "Entred ElseIf Of DocumentType And Check is Equlto DebitNote Or Not";
        public const string Entred_Into_If_Condition_And_Check_Invoice_is_null_or_not = "Entred Into If Condition And Check Invoice is null or not";
        public const string Entred_ElseIf_Condition_And_Check_receiptDetail_Lessthan_detail = "Entred ElseIf Condition And Check receiptDetail Lessthan detail";
        public const string Entred_Into_IfCondition_And_Check_AmmountDue_Is_EqualTo_ReceiptAmount = "Entred Into IfCondition And Check AmmountDue Is EqualTo ReceiptAmount";
        public const string Entred_Into_UpdateReceiptDetails_And_Check_Invoice_is_Null_or_Not = "Entred Into UpdateReceiptDetails And Check Invoice is Null or Not";
        public const string Entred_If_Condition_And_Check_Invoice_Is_Null_Or_Not = "Entred If Condition And Check Invoice Is Null Or Not";
        public const string Entred_Into_Elseif_And_check_AmmountDue_Is_NotEqualTo_ReceiptAmount = "Entred Into Elseif And check AmmountDue Is NotEqualTo ReceiptAmount";
        public const string Entred_Into_Else_And_check_ReceptDetail = "Entred Into Else And check ReceptDetail";
        public const string Entred_Into_If_Condition_And_Check_receiptDetailNew_LessThan_detail = "Entred Into If Condition And Check receiptDetailNew LessThan detail";
        public const string Entred_Into_If_Condition_And_Check_Invoice_Is_Null_Or_Not = "Entred Into If Condition And Check Invoice Is Null Or Not";
        public const string Entred_Elseif_Condition_And_Check_receiptDetailNew_GraterThan_Or_Not = "Entred Elseif Condition And Check receiptDetailNew GraterThan Or Not";
        public const string Entred_Into_If_Condition_And_Check_invoice_Is_Null_Or_Not = "Entred Into If Condition And Check invoice Is Null Or Not";
        public const string Entred_Into_If_Condition_And_check_Invoice_Is_Null_Or_Not = "Entred Into If Condition And Check Invoice Is Null Or Not";
        public const string Entred_Into_ElseIf_And_Check_AmmountDue_Is_Not_Null_ReceiptAmount = "Entred Into ElseIf And Check AmmountDue Is Not Null ReceiptAmount";
        public const string Entered_ElseIf_and_Check_DocumentType = "Entered ElseIf and Check DocumentType";
        public const string Entred_Into_Else_And_Check_Invoice_Is_Not_Null = "Entred Into Else And Check Invoice Is Not Null";
        public const string Entred_Into_ElseIf_And_And_Check_receiptDetailNew_Is_GraterThan_detail_Or_Not = "Entred Into ElseIf And And Check receiptDetailNew Is GraterThan detail Or Not";
        public const string Entered_Into_If_And_Check_AmmountDue_Is_Equal_To_ReceiptAmount = "Entered Into If And Check AmmountDue Is Equal To ReceiptAmount";
        public const string Entred_Into_If_condition_And_Check_Invoice_Is_Null_Or_Not = "Entred Into If condition And Check Invoice Is Null Or Not";
        public const string Entred_Into_ElseIf_Condition_And_Check_AmmountDue_Is_Not_Equal_To_ReceiptAmount = "Entred Into ElseIf Condition And Check AmmountDue Is Not Equal To ReceiptAmount";
        public const string Entred_Into_IfCondition_And_Check_Invoice_Invoice_Is_Null_OR_Not = "Entred Into IfCondition And Check Invoice Invoice Is Null OR Not";
        public const string Entred_Else_If_Condition_And_Check_RecordStatus_Is_Equal_To_Deleted_Or_Not = "Entred Else IfCondition And Check RecordStatus Is Equal To Deleted Or Not";
        public const string Entred_If_Condition_And_Check_receiptDetail_Is_Not_Null_Or_Not = "Entred If Condition And Check receiptDetail Is Not Null Or Not";
        public const string Entred_Into_UpdateReceiptBalancingItems_Method = "Entred Into UpdateReceiptBalancingItems Method";
        public const string Entred_Foreach_Of_ReceiptBalancingItem_Method = "Entred Foreach Of ReceiptBalancingItem Method";
        public const string Entred_If_Condition_And_Check_RecordStatus_IsEqual_To_Added = "Entred If Condition And Check RecordStatus IsEqual To Added";
        public const string Entred_Into_ElseIf_Condition_And_Check_RecordStatus = "Entred Into ElseIf Condition And Check RecordStatus";
        public const string Entred_If_Condition_And_Check_RecordStatus_Is_Added_Or_Deleted = "Entred If Condition And Check RecordStatus Is Added Or Deleted";
        public const string Entred_If_And_Check_RBItem_Is_Null_Or_Not = "Entred If And Check RBItem Is Null Or Not";
        public const string Enter_ElseIf_And_Check_RecordStatus_Is_Equal_To_Deleted_Or_Not = "Enter ElseIf And Check RecordStatus Is Equal To Deleted Or Not";
        public const string Entred_If_Condition_And_Check_receiptBalancingItem_Is_Not_Equal_To_Null_Or_Not = "Entred If Condition And Check receiptBalancingItem Is Not Equal To Null Or Not";
        public const string Entred_Into_UpdateReceiptGSTDetails_Method = "Entred Into UpdateReceiptGSTDetails Method";
        public const string Entred_Into_If_Condition_And_Check_ReceiptGSTDetails_IsNot_Equal_To_Null_Or_Not = "Entred Into If Condition And Check ReceiptGSTDetails IsNot Equal To Null Or Not";
        public const string Entred_Foreach_Of_ReceiptGSTDetail = "Entred Foreach Of ReceiptGSTDetail";
        public const string Entred_Into_If_Condition_And_Check_RecordStatus_is_Added = "Entred Into Else If Condition And Check RecordStatus is Added";
        public const string Entred_If_Condition_And_Check_RecordStatus_Is_Equal_To_Deleted_Or_Not = "Entred If Condition And Check RecordStatus Is Equal To Deleted Or Not";
        public const string Entred_If_Condition_And_Check_receiptGSTDetail_Is_NotEqual_To_Null_Or_Not = "Entred If Condition And Check receiptGSTDetail Is NotEqual To Null Or Not";
        public const string Entred_If_Condition_And_Check_GrandTotal_IsEqual_To_BalanceAmount = "Entred If Condition And Check GrandTotal IsEqual To BalanceAmount";
        public const string Entred_Into_Else_If_Condition_And_Check_GrandTotal_GraterThan_BalanceAmount = "Entred Into Else If Condition And Check GrandTotal GraterThan BalanceAmount";
        public const string Enter_Into_If_Block_And_Check_Invoice_Null_Or_Not = "Enter Into If Block And Check Invoice Null Or Not";
        public const string Entred_Into_Else_If_Condition_And_Check_RecordStatus_is_Not_Eqalto_added_And_Deleted = "Entred Into Else If Condition And Check RecordStatus is Not Eqalto added And Deleted";
        public const string Issues_While_inserting_the_record_in_document_history = "Issues While inserting the record in document history";
        public const string Entering_Into_Saving_DocumentHistory_Block = "Entering into Saving DocumentHistory Block";
        public const string Sucessfully_inserted_the_documents_in_DocumentHistory = "Sucessfully inserted the documents in DocumentHistory";
        public const string Sucessfully_Updated_the_documents_in_DocumentHistory_if_DocDate_is_changed_in_EditMode = "Sucessfully Updated the documents in DocumentHistory if DocDate is changed in Edit Mode";
        public const string ReceiptController = "ReceiptController";
        public const string ReceiptApplicationService = "ReceiptApplicationService";

        #region Receipts
        public const string ReceiptService = "ReceiptService";
        public const string Log_Receipts_GetReceiptsK_Request_Message = "Log Receipts GetReceiptsK Request Message";
        public const string Log_Receipts_SaveCreditNoteDocumentVoidNew_Request_Message = "Log Receipts SaveCreditNoteDocumentVoidNew Request Message";
        public const string Log_Receipts_SaveCreditNoteDocumentVoidNew_Request_Message_Completed = "Log Receipts SaveCreditNoteDocumentVoidNew Request Message Completed";
        public const string Log_Receipts_GetReceiptsApplicationK_Request_Message = "Log Receipts GetReceiptsApplicationK Request Message";
        public const string Log_Receipts_GetReceiptsK_Exeception_Message = "Log Receipts GetReceiptsK Exception Message";
        public const string Log_Receipts_GetReceiptsAllicationK_Exeception_Message = "Log Receipts GetReceiptsAllicationK Exception Message";
        public const string Log_Receipts_CreateReceiptsNewApplication_Request_Message = "Log Receipts CreateReceiptsNewApplication Request Message";
        public const string Log_Receipts_CreateReceiptsNewApplication_Request_Message_Completed = "Log Receipts CreateReceiptsNewApplication Request Message Completed";
        #endregion
    }
}
